### ISSUE TITLE
Installing dependencies for `make ppanalysis`

### ISSUE THREAD

**Issue by qin-yu** [morphometry/papaya2#4]
Is it possible to automatically add libraries by `make`?

For Ubuntu 18.04, before `make ppanalysis` one has to:
```bash
$ sudo apt-get install libcgal-dev
$ sudo apt-get install libccfits-dev
```

---------------------------------------------------------
```
In file included from ppanalysis.cpp:11:0:
voronoi.hpp:11:10: fatal error: CGAL/Delaunay_triangulation_2.h: No such file or directory
 #include <CGAL/Delaunay_triangulation_2.h>
          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make: *** [ppanalysis.o] Error 1
```

```bash
/usr/bin/ld: cannot find -lCCfits
/usr/bin/ld: cannot find -lcfitsio
collect2: error: ld returned 1 exit status
make: *** [ppanalysis] Error 1
```

**Comment by skapfer** [comment]
Hi!

Unfortunately, the actual commands and package names depend a lot on your
distribution.  Also, I don't want to overcomplicate the Makefile (it should
remain simple to understand and modify).

Your point is good though, we should add a few lines to the documentation.

I guess it would be extremely cool to have pre-built deb packages for the
casual user.  We didn't get around to set that up yet...

All the best,

Sebastian

On Thu, May 21, 2020 at 04:03:31AM -0700, Qin Yu wrote:
> Is it possible to automatically add libraries by `make`?
> 
> For Ubuntu 18.04, before `make ppanalysis` one has to:
> ```bash
> $ sudo apt-get install libcgal-dev
> $ sudo apt-get install libccfits-dev
> ```
> 
> ---------------------------------------------------------
> ```
> In file included from ppanalysis.cpp:11:0:
> voronoi.hpp:11:10: fatal error: CGAL/Delaunay_triangulation_2.h: No such file or directory
>  #include <CGAL/Delaunay_triangulation_2.h>
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [ppanalysis.o] Error 1
> ```
> 
> ```bash
> /usr/bin/ld: cannot find -lCCfits
> /usr/bin/ld: cannot find -lcfitsio
> collect2: error: ld returned 1 exit status
> make: *** [ppanalysis] Error 1
> ```
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/morphometry/papaya2/issues/4

-- 
Best regards,               | Theoretische Physik 1, 02.573
  Sebastian Kapfer          | FAU Erlangen
                            | Staudtstr. 7, 91058 Erlangen, Germany
                            | Phone: +49.160.9577.6436
                            | https://theorie1.physik.fau.de/people/skapfer/
                            | GPG: ED891239B22DD0D516F2D9247554541B84406C3F

**Comment by skapfer** [comment]
Hi,

I've added some hints to the troubleshooting section on
https://morphometry.org/software/papaya2/
Hopefully that improves user experience a little.

Also FITS is now only needed for Banana, all the other tools
don't need it anyhow.

Cheers,

Sebastian

On Thu, May 21, 2020 at 04:03:31AM -0700, Qin Yu wrote:
> Is it possible to automatically add libraries by `make`?
> 
> For Ubuntu 18.04, before `make ppanalysis` one has to:
> ```bash
> $ sudo apt-get install libcgal-dev
> $ sudo apt-get install libccfits-dev
> ```
> 
> ---------------------------------------------------------
> ```
> In file included from ppanalysis.cpp:11:0:
> voronoi.hpp:11:10: fatal error: CGAL/Delaunay_triangulation_2.h: No such file or directory
>  #include <CGAL/Delaunay_triangulation_2.h>
>           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> compilation terminated.
> make: *** [ppanalysis.o] Error 1
> ```
> 
> ```bash
> /usr/bin/ld: cannot find -lCCfits
> /usr/bin/ld: cannot find -lcfitsio
> collect2: error: ld returned 1 exit status
> make: *** [ppanalysis] Error 1
> ```
> 
> -- 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/morphometry/papaya2/issues/4

-- 
Best regards,               | Theoretische Physik 1, 02.573
  Sebastian Kapfer          | FAU Erlangen
                            | Staudtstr. 7, 91058 Erlangen, Germany
                            | Phone: +49.160.9577.6436
                            | https://theorie1.physik.fau.de/people/skapfer/
                            | GPG: ED891239B22DD0D516F2D9247554541B84406C3F

**Comment by skapfer** [comment]
For what it's worth, we re-did the Make/configure system. We tried to keep it simple, so no Cmake and stuff, but it should have better instructions and error messages now. Let me know if there's still issues!
